<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Rougamo.Fody" Version="5.0.2" />
		<PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.2" />
	</ItemGroup>

</Project>
