<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- 目标框架改为 .net6.0 并指定为 windows 以启用 WPF -->
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>DrSoft.Docking</RootNamespace>
    <AssemblyName>DrSoft.Docking</AssemblyName>
    <OutputType>Library</OutputType>
    
    <!-- 启用 WPF 支持 -->
    <UseWPF>true</UseWPF>
    
    <!-- 如果代码中使用了 System.Drawing (如 Icon 或 Bitmap) 则开启 -->
    <UseWindowsForms>true</UseWindowsForms>

    <!-- 配置平台和架构 -->
    <Platforms>AnyCPU;x86</Platforms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <!-- 配置资源文件的自动生成逻辑 (ResX) -->
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    
    <Compile Update="Properties\Resources.zh-Hans.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.zh-Hans.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Properties\Resources.zh-Hans.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.zh-Hans.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>


  <ItemGroup>
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>

</Project>