<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\03 Domain\DrSoft.MarkCard.Interface\DrSoft.MarkCard.Interface.csproj" />
    <ProjectReference Include="..\..\03 Domain\DrSoft.MarkCard.Model\DrSoft.MarkCard.Model.csproj" />
    <ProjectReference Include="..\..\99 Components\Drawing\DrSoft.Drawing.Contracts\DrSoft.Drawing.Contracts.csproj" />
    <ProjectReference Include="..\..\99 Components\Drawing\DrSoft.Drawing.Event\DrSoft.Drawing.Event.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
  </ItemGroup>

</Project>
