<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\99 Components\Drawing\DrSoft.Drawing.DTO\DrSoft.Drawing.DTO.csproj" />
    <ProjectReference Include="..\DrSoft.MarkCard.Model\DrSoft.MarkCard.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="config_template.json" />
  </ItemGroup>

</Project>
